spring:
  application:
    name: 'contacts-application'
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${CONTACTS_DB_HOST}:5432/${CONTACTS_DB_NAME}
    username: ${CONTACTS_DB_USER}
    password: ${CONTACTS_DB_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  liquibase:
    change-log: 'liquibase/changelog-master.xml'
    liquibase-schema: 'liquibase_schema'
    default-schema: 'contacts_schema'
