version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: 'contacts-database'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=l3tm31n
      - POSTGRES_DB=contacts
    volumes:
      - './database-initialization:/docker-entrypoint-initdb.d'
