version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: 'contacts-database'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${CONTACTS_DB_NAME}
      - POSTGRES_USER=${CONTACTS_DB_USER}
      - POSTGRES_PASSWORD=${CONTACTS_DB_PASSWORD}
    volumes:
      - './database-initialization:/docker-entrypoint-initdb.d'
    networks:
      - contacts-network
  backend:
    image: contacts-backend
    container_name: 'contacts-backend'
    ports:
      - '8080:8080'
    environment:
      - CONTACTS_DB_HOST=${CONTACTS_DB_HOST}
      - CONTACTS_DB_NAME=${CONTACTS_DB_NAME}
      - CONTACTS_DB_USER=${CONTACTS_DB_USER}
      - CONTACTS_DB_PASSWORD=${CONTACTS_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - contacts-network

networks:
  contacts-network:
    driver: bridge
